### ISSUE TITLE
keypoints_params must be specified error

### ISSUE THREAD

**Issue by alexyao2015** [jacobmarks/fiftyone-albumentations-plugin#5] opened 2024-05-07 06:20 UTC
I can't seem to get this plugin to work without getting this error. I copied this code from the getting started section and accessed the albumentations plugin from the web ui. Am I doing something wrong? 

```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart", max_samples=5)

# only keep the ground truth labels
dataset.select_fields("ground_truth").keep_fields()

session = fo.launch_app(dataset)
session.wait()
```

Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/fiftyone/operators/executor.py", line 277, in execute_or_delegate_operator
    result = await do_execute_operator(operator, ctx, exhaust=exhaust)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fiftyone/operators/executor.py", line 319, in do_execute_operator
    result = await (
             ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fiftyone/core/utils.py", line 2317, in run_sync_task
    return await loop.run_in_executor(_get_sync_task_executor(), func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 1032, in execute
    new_sample_id = transform_sample(sample, transforms, label_fields)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 357, in transform_sample
    transformed = transform(**kwargs)
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/albumentations/core/composition.py", line 499, in __call__
    result = super().__call__(force_apply=force_apply, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/albumentations/core/composition.py", line 215, in __call__
    self._check_args(**data)
  File "/usr/local/lib/python3.12/site-packages/albumentations/core/composition.py", line 304, in _check_args
    raise ValueError(msg)
ValueError: keypoints_params must be specified for keypoint transformations
```

**Comment by jacobmarks** [comment] 2024-05-07 14:29
Hey @alexyao2015 , thanks for logging this. It looks like you tried to apply a keypoint transformation on your dataset when the dataset did not have any keypoint fields, so there was nothing to transform.

If this is not the case, would you mind sharing additional details like:
- what version of FiftyOne you're using
- what version of Albumentations you're using
- what transforms you tried to apply?

**Comment by alexyao2015** [comment] 2024-05-07 14:39
Thanks for the quick response. I tried a number of transformers including `PadIfNeeded` and `Resize`. Below are the versions I'm using. 

fiftyone: 0.23.8
albumentations: 1.4.6

**Comment by jacobmarks** [comment] 2024-05-07 14:42
Okay let me dig into this. Thanks for the heads up. Will get back to you shortly

**Comment by darrenjkt** [comment] 2024-05-08 01:46
Hi jacob, I've encountered the same issue trying to apply the albumentations plugin on a dataset with bounding box labels. I have the same fiftyone and albumentations versions as alex.

I've tried with CenterCrop(height=250,width=250,p=1) and Flip(p=0.5) but both give the same error of `ValueError: keypoints_params must be specified for keypoint transformations`. These transforms aren't specific to keypoint labels so I thought they should work.

**Comment by jacobmarks** [comment] 2024-05-08 02:33
@darrenjkt @alexyao2015 this should now be fixed. 

The issue is that in the latest Albumentations release, `keypoints_params` went from being optional to being required. [Here](https://albumentations.ai/docs/getting_started/keypoints_augmentation/#step-2-define-an-augmentation-pipeline) is the new minimal example.

To use the latest version of the plugin, the easiest option is through the UI. Install the "plugins" plugin, which is used to manage plugins (lol). 

```bash
fiftyone plugins download \
    https://github.com/voxel51/fiftyone-plugins \
    --plugin-names @voxel51/plugins
```

Then use the `install_plugin` operator. Go to the community tab and select Albumentations plugin from the dropdown. You should see something like this:
<img width="1728" alt="Screenshot 2024-05-07 at 10 32 16 PM" src="https://github.com/jacobmarks/fiftyone-albumentations-plugin/assets/12500356/80ee1664-c140-42fd-a328-60687f0d968e">

Let me know if you are still running into issues!

**Comment by alexyao2015** [comment] 2024-05-08 04:08
Thank you! It seems like I no longer see that issue anymore. Unfortunately, I seem to get another error when running `PadIfNeeded`. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/fiftyone/operators/executor.py", line 277, in execute_or_delegate_operator
    result = await do_execute_operator(operator, ctx, exhaust=exhaust)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fiftyone/operators/executor.py", line 319, in do_execute_operator
    result = await (
             ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fiftyone/core/utils.py", line 2317, in run_sync_task
    return await loop.run_in_executor(_get_sync_task_executor(), func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 1035, in execute
    new_sample_id = transform_sample(sample, transforms, label_fields)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 420, in transform_sample
    sample._dataset.add_sample(new_sample)
  File "/usr/local/lib/python3.12/site-packages/fiftyone/core/dataset.py", line 2495, in add_sample
    ids = self._add_samples_batch(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fiftyone/core/dataset.py", line 2623, in _add_samples_batch
    self._sample_collection.insert_many(dicts)
  File "/usr/local/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/collection.py", line 742, in insert_many
    blk.execute(write_concern, session, _Op.INSERT)
  File "/usr/local/lib/python3.12/site-packages/pymongo/bulk.py", line 595, in execute
    return self.execute_command(generator, write_concern, session, operation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/bulk.py", line 452, in execute_command
    client._retryable_write(
  File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1569, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1455, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1501, in _retry_internal
    ).run()
      ^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2347, in run
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2464, in _write
    return self._func(self._session, conn, self._retryable)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/bulk.py", line 441, in retryable_bulk
    self._execute_command(
  File "/usr/local/lib/python3.12/site-packages/pymongo/bulk.py", line 386, in _execute_command
    result, to_send = bwc.execute(cmd, ops, client)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/message.py", line 959, in execute
    request_id, msg, to_send = self.__batch_command(cmd, docs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/message.py", line 949, in __batch_command
    request_id, msg, to_send = _do_batched_op_msg(
                               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymongo/message.py", line 1451, in _do_batched_op_msg
    return _batched_op_msg(operation, command, docs, ack, opts, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bson.errors.InvalidDocument: cannot encode object: <PositionType.CENTER: 'center'>, of type: <enum 'PositionType'>
```

**Comment by darrenjkt** [comment] 2024-05-08 04:43
Works well for me now! Thanks for the prompt fix.

**Comment by jacobmarks** [comment] 2024-05-08 04:52
> Works well for me now! Thanks for the prompt fix.

Awesome @darrenjkt , so glad :)

**Comment by jacobmarks** [comment] 2024-05-08 04:52
> Thank you! It seems like I no longer see that issue anymore. Unfortunately, I seem to get another error when running `PadIfNeeded`.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/fiftyone/operators/executor.py", line 277, in execute_or_delegate_operator
>     result = await do_execute_operator(operator, ctx, exhaust=exhaust)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/fiftyone/operators/executor.py", line 319, in do_execute_operator
>     result = await (
>              ^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/fiftyone/core/utils.py", line 2317, in run_sync_task
>     return await loop.run_in_executor(_get_sync_task_executor(), func, *args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 1035, in execute
>     new_sample_id = transform_sample(sample, transforms, label_fields)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 420, in transform_sample
>     sample._dataset.add_sample(new_sample)
>   File "/usr/local/lib/python3.12/site-packages/fiftyone/core/dataset.py", line 2495, in add_sample
>     ids = self._add_samples_batch(
>           ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/fiftyone/core/dataset.py", line 2623, in _add_samples_batch
>     self._sample_collection.insert_many(dicts)
>   File "/usr/local/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
>     return func(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/collection.py", line 742, in insert_many
>     blk.execute(write_concern, session, _Op.INSERT)
>   File "/usr/local/lib/python3.12/site-packages/pymongo/bulk.py", line 595, in execute
>     return self.execute_command(generator, write_concern, session, operation)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/bulk.py", line 452, in execute_command
>     client._retryable_write(
>   File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1569, in _retryable_write
>     return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1455, in _retry_with_session
>     return self._retry_internal(
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
>     return func(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1501, in _retry_internal
>     ).run()
>       ^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2347, in run
>     return self._read() if self._is_read else self._write()
>                                               ^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2464, in _write
>     return self._func(self._session, conn, self._retryable)  # type: ignore
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/bulk.py", line 441, in retryable_bulk
>     self._execute_command(
>   File "/usr/local/lib/python3.12/site-packages/pymongo/bulk.py", line 386, in _execute_command
>     result, to_send = bwc.execute(cmd, ops, client)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/message.py", line 959, in execute
>     request_id, msg, to_send = self.__batch_command(cmd, docs)
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/message.py", line 949, in __batch_command
>     request_id, msg, to_send = _do_batched_op_msg(
>                                ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pymongo/message.py", line 1451, in _do_batched_op_msg
>     return _batched_op_msg(operation, command, docs, ack, opts, ctx)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> bson.errors.InvalidDocument: cannot encode object: <PositionType.CENTER: 'center'>, of type: <enum 'PositionType'>
> ```

Will check this out tomorrow @alexyao2015 .

**Comment by jacobmarks** [comment] 2024-05-08 14:49
Hey @alexyao2015 , this should be fixed now. It looks like a `PositionType` enum was added to Albumentations which did not readily serialize. The latest version of this plugin creates a serialized record of this :)

**Closed as completed by jacobmarks** 2024-05-08 14:49 UTC
